# Generated by Django 6.0 on 2025-12-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
