# Generated by Django 6.0 on 2025-12-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tarefa_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarefa",
            options={"ordering": ["prazo"]},
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(
                blank=True, help_text="Detalhes ou briefing", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="prazo",
            field=models.DateTimeField(help_text="Data limite"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Ex: Urgente, Instagram",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="titulo",
            field=models.CharField(help_text="Título da demanda", max_length=200),
        ),
    ]
